-- M11-S04 organization-scoped service accounts and inbound customer/activity
-- commands. Bearer tokens are generated by the trusted runtime, retained only
-- as SHA-256 digests, and resolved to tenant authority inside PostgreSQL.

alter table loyalty.commerce_connections
  drop constraint commerce_connections_platform_check;
alter table loyalty.commerce_connections
  add constraint commerce_connections_platform_check
  check (platform in ('woocommerce', 'merchant_activity', 'service_api'));

create table loyalty.service_accounts (
  id bigint generated always as identity primary key,
  public_id uuid not null default gen_random_uuid() unique,
  organization_id bigint not null references loyalty.organizations(id) on delete cascade,
  workspace_id bigint not null,
  programme_id bigint not null,
  connection_id bigint not null,
  display_name text not null,
  scopes text[] not null,
  requests_per_minute integer not null,
  status text not null default 'active' check (status in ('active', 'revoked')),
  created_by_user_id uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  revoked_at timestamptz,
  unique (organization_id, id),
  unique (organization_id, public_id),
  foreign key (organization_id, workspace_id)
    references loyalty.workspaces(organization_id, id) on delete restrict,
  foreign key (organization_id, programme_id)
    references loyalty.programmes(organization_id, id) on delete restrict,
  foreign key (organization_id, connection_id)
    references loyalty.commerce_connections(organization_id, id) on delete restrict,
  check (length(btrim(display_name)) between 1 and 200),
  check (display_name !~ '[[:cntrl:]]'),
  check (cardinality(scopes) between 1 and 2),
  check (scopes <@ array['activities:write', 'customers:write']::text[]),
  check (cardinality(scopes) = 1 or scopes[1] <> scopes[2]),
  check (requests_per_minute between 10 and 6000),
  check ((status = 'revoked') = (revoked_at is not null)),
  check (revoked_at is null or revoked_at >= created_at)
);

create index service_accounts_tenant_status_idx
  on loyalty.service_accounts (organization_id, status, created_at desc, id desc);

create table loyalty_private.service_account_credentials (
  id bigint generated always as identity primary key,
  public_id uuid not null default gen_random_uuid() unique,
  organization_id bigint not null references loyalty.organizations(id) on delete cascade,
  service_account_id bigint not null,
  token_sha256 bytea not null unique check (octet_length(token_sha256) = 32),
  secret_hint text not null check (secret_hint ~ '^[A-Za-z0-9_-]{6}$'),
  status text not null default 'active'
    check (status in ('active', 'retiring', 'revoked')),
  valid_until timestamptz,
  created_by_user_id uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  revoked_at timestamptz,
  unique (organization_id, id),
  unique (organization_id, service_account_id, public_id),
  foreign key (organization_id, service_account_id)
    references loyalty.service_accounts(organization_id, id) on delete cascade,
  check (
    (status = 'active' and valid_until is null and revoked_at is null)
    or (status = 'retiring' and valid_until is not null and revoked_at is null)
    or (status = 'revoked' and valid_until is not null and revoked_at is not null)
  ),
  check (valid_until is null or valid_until >= created_at),
  check (revoked_at is null or revoked_at >= created_at)
);

create index service_account_credentials_current_idx
  on loyalty_private.service_account_credentials (
    organization_id, service_account_id, status, valid_until, id desc
  );

create table loyalty_private.service_account_identity_peppers (
  organization_id bigint not null references loyalty.organizations(id) on delete cascade,
  service_account_id bigint not null,
  pepper bytea not null default extensions.gen_random_bytes(32)
    check (octet_length(pepper) = 32),
  created_at timestamptz not null default now(),
  primary key (service_account_id),
  unique (organization_id, service_account_id),
  foreign key (organization_id, service_account_id)
    references loyalty.service_accounts(organization_id, id) on delete cascade
);

create table loyalty_private.service_customer_identities (
  id bigint generated always as identity primary key,
  public_id uuid not null default gen_random_uuid() unique,
  organization_id bigint not null references loyalty.organizations(id) on delete cascade,
  service_account_id bigint not null,
  customer_id bigint not null,
  external_customer_sha256 bytea not null check (octet_length(external_customer_sha256) = 32),
  created_at timestamptz not null default now(),
  unique (organization_id, id),
  unique (organization_id, service_account_id, external_customer_sha256),
  foreign key (organization_id, service_account_id)
    references loyalty.service_accounts(organization_id, id) on delete restrict,
  foreign key (organization_id, customer_id)
    references loyalty.customers(organization_id, id) on delete restrict
);

create index service_customer_identities_customer_idx
  on loyalty_private.service_customer_identities (
    organization_id, customer_id, service_account_id, id
  );

create table loyalty_private.service_customer_command_receipts (
  id bigint generated always as identity primary key,
  public_id uuid not null default gen_random_uuid() unique,
  organization_id bigint not null references loyalty.organizations(id) on delete cascade,
  service_account_id bigint not null,
  customer_id bigint not null,
  external_customer_sha256 bytea not null check (octet_length(external_customer_sha256) = 32),
  idempotency_key text not null,
  request_sha256 bytea not null check (octet_length(request_sha256) = 32),
  original_outcome text not null check (original_outcome in ('created', 'existing')),
  correlation_id uuid not null,
  created_at timestamptz not null default now(),
  unique (organization_id, id),
  unique (organization_id, service_account_id, idempotency_key),
  foreign key (organization_id, service_account_id)
    references loyalty.service_accounts(organization_id, id) on delete restrict,
  foreign key (organization_id, customer_id)
    references loyalty.customers(organization_id, id) on delete restrict,
  check (length(idempotency_key) between 1 and 255)
);

create table loyalty_private.service_account_rate_windows (
  organization_id bigint not null references loyalty.organizations(id) on delete cascade,
  credential_id bigint not null,
  window_started_at timestamptz not null,
  request_count integer not null check (request_count between 1 and 6000),
  updated_at timestamptz not null default now(),
  primary key (credential_id, window_started_at),
  foreign key (organization_id, credential_id)
    references loyalty_private.service_account_credentials(organization_id, id) on delete cascade,
  check (updated_at >= window_started_at)
);

alter table loyalty.service_accounts owner to loyalty_owner;
alter table loyalty_private.service_account_credentials owner to loyalty_owner;
alter table loyalty_private.service_account_identity_peppers owner to loyalty_owner;
alter table loyalty_private.service_customer_identities owner to loyalty_owner;
alter table loyalty_private.service_customer_command_receipts owner to loyalty_owner;
alter table loyalty_private.service_account_rate_windows owner to loyalty_owner;

alter table loyalty.service_accounts enable row level security;
alter table loyalty_private.service_account_credentials enable row level security;
alter table loyalty_private.service_account_identity_peppers enable row level security;
alter table loyalty_private.service_customer_identities enable row level security;
alter table loyalty_private.service_customer_command_receipts enable row level security;
alter table loyalty_private.service_account_rate_windows enable row level security;

create policy service_accounts_owner_admin_select
  on loyalty.service_accounts
  for select
  to authenticated
  using ((select loyalty_private.has_organization_role(
    organization_id, array['owner', 'admin']::text[]
  )));

create trigger service_accounts_immutable
before update or delete on loyalty.service_accounts
for each row execute function loyalty_private.reject_immutable_change();

create trigger service_customer_identities_immutable
before update or delete on loyalty_private.service_customer_identities
for each row execute function loyalty_private.reject_immutable_change();

create trigger service_customer_command_receipts_immutable
before update or delete on loyalty_private.service_customer_command_receipts
for each row execute function loyalty_private.reject_immutable_change();

create or replace function loyalty_private.protect_service_account_credential()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if old.id <> new.id or old.public_id <> new.public_id
    or old.organization_id <> new.organization_id
    or old.service_account_id <> new.service_account_id
    or old.token_sha256 <> new.token_sha256
    or old.secret_hint <> new.secret_hint
    or old.created_by_user_id <> new.created_by_user_id
    or old.created_at <> new.created_at then
    raise exception using errcode = '55000', message = 'service credential material is immutable';
  end if;
  if old.status = 'revoked' and new.status <> 'revoked' then
    raise exception using errcode = '55000', message = 'revoked service credential cannot be restored';
  end if;
  if old.valid_until is not null and new.valid_until is not null
    and new.valid_until > old.valid_until then
    raise exception using errcode = '55000', message = 'service credential validity cannot be extended';
  end if;
  return new;
end;
$$;

create trigger service_account_credentials_protect
before update on loyalty_private.service_account_credentials
for each row execute function loyalty_private.protect_service_account_credential();

create trigger service_account_credentials_no_delete
before delete on loyalty_private.service_account_credentials
for each row execute function loyalty_private.reject_immutable_change();

create trigger service_account_identity_peppers_immutable
before update or delete on loyalty_private.service_account_identity_peppers
for each row execute function loyalty_private.reject_immutable_change();

create or replace function loyalty_private.create_service_account_v1(
  target_actor_user_id uuid,
  target_workspace_public_id uuid,
  target_programme_public_id uuid,
  target_display_name text,
  target_scopes text[],
  target_requests_per_minute integer,
  target_idempotency_key text,
  target_correlation_id uuid
)
returns table (service_account_public_id uuid, outcome text)
language plpgsql
security definer
set search_path = ''
set statement_timeout = '5s'
as $$
declare
  target_workspace loyalty.workspaces%rowtype;
  target_programme loyalty.programmes%rowtype;
  target_connection loyalty.commerce_connections%rowtype;
  target_organization_public_id uuid;
  canonical_scopes text[];
  entitlement_enabled boolean;
  request_hash bytea;
  existing_audit loyalty.admin_audit_events%rowtype;
  created_account loyalty.service_accounts%rowtype;
  command_time timestamptz := clock_timestamp();
begin
  select coalesce(array_agg(scope order by scope), array[]::text[])
  into canonical_scopes
  from (select distinct unnest(target_scopes) as scope) as requested;
  if target_actor_user_id is null or target_workspace_public_id is null
    or target_programme_public_id is null or target_display_name is null
    or target_display_name <> btrim(target_display_name)
    or length(target_display_name) not between 1 and 200
    or target_display_name ~ '[[:cntrl:]]'
    or target_scopes is null
    or exists (select 1 from unnest(target_scopes) as scope where scope is null)
    or cardinality(target_scopes) <> cardinality(canonical_scopes)
    or cardinality(canonical_scopes) not between 1 and 2
    or not (canonical_scopes <@ array['activities:write', 'customers:write']::text[])
    or target_requests_per_minute is null
    or target_requests_per_minute not between 10 and 6000
    or target_idempotency_key is null
    or target_idempotency_key <> btrim(target_idempotency_key)
    or length(target_idempotency_key) not between 1 and 255
    or target_correlation_id is null then
    raise exception using errcode = '22023', message = 'invalid service account command';
  end if;

  select workspace.* into target_workspace
  from loyalty.workspaces as workspace
  where workspace.public_id = target_workspace_public_id
    and workspace.status = 'active';
  if not found then
    raise exception using errcode = '42501', message = 'service account command not authorized';
  end if;
  select programme.* into target_programme
  from loyalty.programmes as programme
  join loyalty.programme_group_workspaces as group_workspace
    on group_workspace.organization_id = programme.organization_id
   and group_workspace.programme_group_id = programme.programme_group_id
   and group_workspace.workspace_id = target_workspace.id
  where programme.public_id = target_programme_public_id
    and programme.organization_id = target_workspace.organization_id
    and programme.status = 'active'
    and exists (
      select 1 from loyalty.programme_versions as version
      where version.organization_id = programme.organization_id
        and version.programme_id = programme.id
        and version.status = 'published'
        and version.configuration ->> 'version' = '2'
    );
  if not found or not exists (
    select 1 from loyalty.organization_memberships as membership
    where membership.organization_id = target_workspace.organization_id
      and membership.user_id = target_actor_user_id
      and membership.role in ('owner', 'admin')
      and membership.revoked_at is null
  ) then
    raise exception using errcode = '42501', message = 'service account command not authorized';
  end if;

  select organization.public_id into strict target_organization_public_id
  from loyalty.organizations as organization
  where organization.id = target_workspace.organization_id
    and organization.status = 'active';
  select entitlement.enabled into entitlement_enabled
  from loyalty_private.resolve_organization_entitlement(
    target_workspace.organization_id, 'ecosystem.api',
    target_organization_public_id::text, command_time
  ) as entitlement;
  if not coalesce(entitlement_enabled, false) then
    raise exception using errcode = '42501', message = 'ecosystem capability disabled';
  end if;

  request_hash := extensions.digest(convert_to(
    'service-account.create|' || target_workspace.public_id::text || '|' ||
      target_programme.public_id::text || '|' || target_display_name || '|' ||
      array_to_string(canonical_scopes, ',') || '|' || target_requests_per_minute::text,
    'UTF8'
  ), 'sha256');
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
    'service-account-idempotency|' || target_workspace.organization_id::text ||
      '|' || target_idempotency_key,
    0
  ));
  select audit.* into existing_audit
  from loyalty.admin_audit_events as audit
  where audit.organization_id = target_workspace.organization_id
    and audit.idempotency_key = target_idempotency_key;
  if found then
    if existing_audit.action <> 'service_account.create'
      or existing_audit.request_sha256 <> request_hash then
      raise exception using errcode = '23514', message = 'service account idempotency conflict';
    end if;
    return query select account.public_id, 'duplicate'::text
    from loyalty.service_accounts as account
    where account.organization_id = target_workspace.organization_id
      and account.public_id = existing_audit.resource_public_id;
    return;
  end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
    'service-api-connection|' || target_workspace.organization_id::text ||
      '|' || target_workspace.id::text,
    0
  ));
  select connection.* into target_connection
  from loyalty.commerce_connections as connection
  where connection.organization_id = target_workspace.organization_id
    and connection.workspace_id = target_workspace.id
    and connection.platform = 'service_api'
  for update;
  if not found then
    insert into loyalty.commerce_connections (
      organization_id, workspace_id, platform, external_store_id,
      display_name, status, current_key_version, signing_material_ref,
      programme_id
    ) values (
      target_workspace.organization_id, target_workspace.id, 'service_api',
      'service-api:' || target_workspace.public_id::text,
      'Service API', 'active', 'v1',
      'service-api:' || target_workspace.public_id::text || ':no-secret',
      target_programme.id
    ) returning * into strict target_connection;
  elsif target_connection.programme_id <> target_programme.id
    or target_connection.status not in ('active', 'rotating') then
    raise exception using errcode = '23514', message = 'service API workspace scope unavailable';
  end if;

  insert into loyalty.service_accounts (
    organization_id, workspace_id, programme_id, connection_id,
    display_name, scopes, requests_per_minute, created_by_user_id,
    created_at
  ) values (
    target_workspace.organization_id, target_workspace.id,
    target_programme.id, target_connection.id, target_display_name,
    canonical_scopes, target_requests_per_minute, target_actor_user_id,
    command_time
  ) returning * into strict created_account;
  insert into loyalty_private.service_account_identity_peppers (
    organization_id, service_account_id, created_at
  ) values (
    created_account.organization_id, created_account.id, command_time
  );
  insert into loyalty.admin_audit_events (
    organization_id, actor_user_id, action, resource_type,
    resource_public_id, idempotency_key, request_sha256, correlation_id,
    metadata, created_at
  ) values (
    created_account.organization_id, target_actor_user_id,
    'service_account.create', 'service_account', created_account.public_id,
    target_idempotency_key, request_hash, target_correlation_id,
    jsonb_build_object(
      'workspaceId', target_workspace.public_id,
      'programmeId', target_programme.public_id,
      'scopes', canonical_scopes,
      'requestsPerMinute', created_account.requests_per_minute
    ), command_time
  );
  return query select created_account.public_id, 'created'::text;
end;
$$;

create or replace function loyalty_private.issue_service_account_credential_v1(
  target_actor_user_id uuid,
  target_service_account_public_id uuid,
  target_credential_public_id uuid,
  target_token_sha256 bytea,
  target_secret_hint text,
  target_overlap_seconds integer,
  target_idempotency_key text,
  target_correlation_id uuid
)
returns table (
  credential_public_id uuid,
  secret_hint text,
  outcome text,
  prior_valid_until timestamptz
)
language plpgsql
security definer
set search_path = ''
set statement_timeout = '5s'
as $$
declare
  target_account loyalty.service_accounts%rowtype;
  target_organization_public_id uuid;
  entitlement_enabled boolean;
  request_hash bytea;
  existing_audit loyalty.admin_audit_events%rowtype;
  existing_credential loyalty_private.service_account_credentials%rowtype;
  created_credential loyalty_private.service_account_credentials%rowtype;
  retiring_until timestamptz;
  command_time timestamptz := clock_timestamp();
begin
  if target_actor_user_id is null or target_service_account_public_id is null
    or target_credential_public_id is null or target_token_sha256 is null
    or octet_length(target_token_sha256) <> 32
    or target_secret_hint is null
    or target_secret_hint !~ '^[A-Za-z0-9_-]{6}$'
    or target_overlap_seconds is null
    or target_overlap_seconds not between 0 and 86400
    or target_idempotency_key is null
    or target_idempotency_key <> btrim(target_idempotency_key)
    or length(target_idempotency_key) not between 1 and 255
    or target_correlation_id is null then
    raise exception using errcode = '22023', message = 'invalid service credential command';
  end if;
  select account.* into target_account
  from loyalty.service_accounts as account
  join loyalty.organizations as organization
    on organization.id = account.organization_id
   and organization.status = 'active'
  join loyalty.workspaces as workspace
    on workspace.organization_id = account.organization_id
   and workspace.id = account.workspace_id
   and workspace.status = 'active'
  where account.public_id = target_service_account_public_id
    and account.status = 'active'
    and exists (
      select 1 from loyalty.organization_memberships as membership
      where membership.organization_id = account.organization_id
        and membership.user_id = target_actor_user_id
        and membership.role in ('owner', 'admin')
        and membership.revoked_at is null
    )
  for update of account;
  if not found then
    raise exception using errcode = '42501', message = 'service credential command not authorized';
  end if;
  select organization.public_id into strict target_organization_public_id
  from loyalty.organizations as organization
  where organization.id = target_account.organization_id;
  select entitlement.enabled into entitlement_enabled
  from loyalty_private.resolve_organization_entitlement(
    target_account.organization_id, 'ecosystem.api',
    target_organization_public_id::text, command_time
  ) as entitlement;
  if not coalesce(entitlement_enabled, false) then
    raise exception using errcode = '42501', message = 'ecosystem capability disabled';
  end if;

  request_hash := extensions.digest(convert_to(
    'service-credential.issue|' || target_account.public_id::text || '|' ||
      target_overlap_seconds::text,
    'UTF8'
  ), 'sha256');
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
    'service-credential-idempotency|' || target_account.organization_id::text ||
      '|' || target_idempotency_key,
    0
  ));
  select audit.* into existing_audit
  from loyalty.admin_audit_events as audit
  where audit.organization_id = target_account.organization_id
    and audit.idempotency_key = target_idempotency_key;
  if found then
    if existing_audit.action <> 'service_account.credential.issue'
      or existing_audit.request_sha256 <> request_hash then
      raise exception using errcode = '23514', message = 'service credential idempotency conflict';
    end if;
    select credential.* into strict existing_credential
    from loyalty_private.service_account_credentials as credential
    where credential.organization_id = target_account.organization_id
      and credential.public_id = existing_audit.resource_public_id;
    return query select existing_credential.public_id,
      existing_credential.secret_hint, 'duplicate'::text,
      null::timestamptz;
    return;
  end if;

  retiring_until := command_time + pg_catalog.make_interval(secs => target_overlap_seconds);
  if target_overlap_seconds = 0 then
    update loyalty_private.service_account_credentials as credential
    set status = 'revoked', valid_until = command_time, revoked_at = command_time
    where credential.organization_id = target_account.organization_id
      and credential.service_account_id = target_account.id
      and credential.status in ('active', 'retiring');
  else
    update loyalty_private.service_account_credentials as credential
    set status = 'retiring',
        valid_until = least(coalesce(credential.valid_until, retiring_until), retiring_until)
    where credential.organization_id = target_account.organization_id
      and credential.service_account_id = target_account.id
      and credential.status in ('active', 'retiring');
  end if;

  insert into loyalty_private.service_account_credentials (
    public_id, organization_id, service_account_id, token_sha256,
    secret_hint, status, created_by_user_id, created_at
  ) values (
    target_credential_public_id, target_account.organization_id,
    target_account.id, target_token_sha256, target_secret_hint, 'active',
    target_actor_user_id, command_time
  ) returning * into strict created_credential;
  insert into loyalty.admin_audit_events (
    organization_id, actor_user_id, action, resource_type,
    resource_public_id, idempotency_key, request_sha256, correlation_id,
    metadata, created_at
  ) values (
    target_account.organization_id, target_actor_user_id,
    'service_account.credential.issue', 'service_account_credential',
    created_credential.public_id, target_idempotency_key, request_hash,
    target_correlation_id,
    jsonb_build_object(
      'serviceAccountId', target_account.public_id,
      'secretHint', created_credential.secret_hint,
      'overlapSeconds', target_overlap_seconds
    ), command_time
  );
  return query select created_credential.public_id,
    created_credential.secret_hint, 'created'::text,
    case when target_overlap_seconds = 0 then command_time else retiring_until end;
end;
$$;

create or replace function loyalty_private.revoke_service_account_credential_v1(
  target_actor_user_id uuid,
  target_service_account_public_id uuid,
  target_credential_public_id uuid,
  target_reason text,
  target_idempotency_key text,
  target_correlation_id uuid
)
returns table (credential_public_id uuid, outcome text, status text)
language plpgsql
security definer
set search_path = ''
set statement_timeout = '5s'
as $$
declare
  target_account loyalty.service_accounts%rowtype;
  target_credential loyalty_private.service_account_credentials%rowtype;
  existing_audit loyalty.admin_audit_events%rowtype;
  request_hash bytea;
  command_outcome text;
  command_time timestamptz := clock_timestamp();
begin
  if target_actor_user_id is null or target_service_account_public_id is null
    or target_credential_public_id is null or target_reason is null
    or target_reason <> btrim(target_reason)
    or length(target_reason) not between 1 and 200
    or target_reason ~ '[[:cntrl:]]'
    or target_idempotency_key is null
    or target_idempotency_key <> btrim(target_idempotency_key)
    or length(target_idempotency_key) not between 1 and 255
    or target_correlation_id is null then
    raise exception using errcode = '22023', message = 'invalid service credential revocation';
  end if;
  select account.* into target_account
  from loyalty.service_accounts as account
  where account.public_id = target_service_account_public_id
    and exists (
      select 1 from loyalty.organization_memberships as membership
      where membership.organization_id = account.organization_id
        and membership.user_id = target_actor_user_id
        and membership.role in ('owner', 'admin')
        and membership.revoked_at is null
    )
  for update;
  if not found then
    raise exception using errcode = '42501', message = 'service credential revocation not authorized';
  end if;
  request_hash := extensions.digest(convert_to(
    'service-credential.revoke|' || target_account.public_id::text || '|' ||
      target_credential_public_id::text || '|' || target_reason,
    'UTF8'
  ), 'sha256');
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
    'service-credential-idempotency|' || target_account.organization_id::text ||
      '|' || target_idempotency_key,
    0
  ));
  select audit.* into existing_audit
  from loyalty.admin_audit_events as audit
  where audit.organization_id = target_account.organization_id
    and audit.idempotency_key = target_idempotency_key;
  if found then
    if existing_audit.action <> 'service_account.credential.revoke'
      or existing_audit.request_sha256 <> request_hash then
      raise exception using errcode = '23514', message = 'service credential revocation idempotency conflict';
    end if;
    return query select credential.public_id, 'duplicate'::text,
      credential.status
    from loyalty_private.service_account_credentials as credential
    where credential.organization_id = target_account.organization_id
      and credential.public_id = existing_audit.resource_public_id;
    return;
  end if;
  select credential.* into target_credential
  from loyalty_private.service_account_credentials as credential
  where credential.organization_id = target_account.organization_id
    and credential.service_account_id = target_account.id
    and credential.public_id = target_credential_public_id
  for update;
  if not found then
    raise exception using errcode = '42501', message = 'service credential revocation not authorized';
  end if;
  command_outcome := case when target_credential.status = 'revoked'
    then 'already_revoked' else 'revoked' end;
  if target_credential.status <> 'revoked' then
    update loyalty_private.service_account_credentials
    set status = 'revoked', valid_until = command_time, revoked_at = command_time
    where id = target_credential.id
    returning * into strict target_credential;
  end if;
  insert into loyalty.admin_audit_events (
    organization_id, actor_user_id, action, resource_type,
    resource_public_id, idempotency_key, request_sha256, correlation_id,
    metadata, created_at
  ) values (
    target_account.organization_id, target_actor_user_id,
    'service_account.credential.revoke', 'service_account_credential',
    target_credential.public_id, target_idempotency_key, request_hash,
    target_correlation_id,
    jsonb_build_object(
      'serviceAccountId', target_account.public_id,
      'reason', target_reason,
      'outcome', command_outcome
    ), command_time
  );
  return query select target_credential.public_id, command_outcome,
    target_credential.status;
end;
$$;

create or replace function loyalty_private.authorize_service_account_request_v1(
  target_credential_public_id uuid,
  target_token_sha256 bytea,
  target_required_scope text
)
returns table (
  service_account_id bigint,
  service_account_public_id uuid,
  organization_id bigint,
  connection_id bigint,
  connection_public_id uuid,
  credential_public_id uuid,
  quota_limit integer,
  quota_remaining integer,
  quota_reset_at timestamptz
)
language plpgsql
security definer
set search_path = ''
set statement_timeout = '5s'
as $$
declare
  target_account loyalty.service_accounts%rowtype;
  target_credential loyalty_private.service_account_credentials%rowtype;
  target_connection loyalty.commerce_connections%rowtype;
  target_organization_public_id uuid;
  entitlement_enabled boolean;
  window_start timestamptz;
  used_count integer;
  command_time timestamptz := clock_timestamp();
begin
  if target_credential_public_id is null or target_token_sha256 is null
    or octet_length(target_token_sha256) <> 32
    or target_required_scope not in ('activities:write', 'customers:write') then
    raise exception using errcode = '28000', message = 'invalid service credential';
  end if;
  select credential.* into target_credential
  from loyalty_private.service_account_credentials as credential
  where credential.public_id = target_credential_public_id
    and credential.token_sha256 = target_token_sha256
    and (
      credential.status = 'active'
      or (credential.status = 'retiring' and credential.valid_until > command_time)
    )
  for update;
  if not found then
    raise exception using errcode = '28000', message = 'invalid service credential';
  end if;
  select account.* into target_account
  from loyalty.service_accounts as account
  join loyalty.organizations as organization
    on organization.id = account.organization_id
   and organization.status = 'active'
  join loyalty.workspaces as workspace
    on workspace.organization_id = account.organization_id
   and workspace.id = account.workspace_id
   and workspace.status = 'active'
  join loyalty.programmes as programme
    on programme.organization_id = account.organization_id
   and programme.id = account.programme_id
   and programme.status = 'active'
  where account.organization_id = target_credential.organization_id
    and account.id = target_credential.service_account_id
    and account.status = 'active'
    and target_required_scope = any(account.scopes)
    and exists (
      select 1 from loyalty.programme_versions as version
      where version.organization_id = account.organization_id
        and version.programme_id = account.programme_id
        and version.status = 'published'
        and version.configuration ->> 'version' = '2'
    )
  for update of account;
  if not found then
    raise exception using errcode = '42501', message = 'service account scope unavailable';
  end if;
  select connection.* into target_connection
  from loyalty.commerce_connections as connection
  where connection.organization_id = target_account.organization_id
    and connection.id = target_account.connection_id
    and connection.workspace_id = target_account.workspace_id
    and connection.programme_id = target_account.programme_id
    and connection.platform = 'service_api'
    and connection.status in ('active', 'rotating')
  for update;
  if not found then
    raise exception using errcode = '42501', message = 'service account scope unavailable';
  end if;
  select organization.public_id into strict target_organization_public_id
  from loyalty.organizations as organization
  where organization.id = target_account.organization_id;
  select entitlement.enabled into entitlement_enabled
  from loyalty_private.resolve_organization_entitlement(
    target_account.organization_id, 'ecosystem.api',
    target_organization_public_id::text, command_time
  ) as entitlement;
  if not coalesce(entitlement_enabled, false) then
    raise exception using errcode = '42501', message = 'ecosystem capability disabled';
  end if;

  window_start := pg_catalog.date_bin(
    interval '1 minute', command_time, timestamptz '1970-01-01 00:00:00+00'
  );
  insert into loyalty_private.service_account_rate_windows (
    organization_id, credential_id, window_started_at, request_count, updated_at
  ) values (
    target_account.organization_id, target_credential.id, window_start, 1,
    command_time
  )
  on conflict (credential_id, window_started_at) do update
    set request_count = service_account_rate_windows.request_count + 1,
        updated_at = command_time
    where service_account_rate_windows.request_count < target_account.requests_per_minute
  returning request_count into used_count;
  if used_count is null then
    raise exception using errcode = 'P0001', message = 'service account rate limit exceeded';
  end if;

  return query select target_account.id, target_account.public_id,
    target_account.organization_id, target_connection.id,
    target_connection.public_id, target_credential.public_id,
    target_account.requests_per_minute,
    target_account.requests_per_minute - used_count,
    window_start + interval '1 minute';
end;
$$;

create or replace function loyalty_private.upsert_service_customer_v1(
  target_credential_public_id uuid,
  target_token_sha256 bytea,
  target_external_customer_id text,
  target_idempotency_key text,
  target_correlation_id uuid
)
returns table (
  customer_public_id uuid,
  outcome text,
  quota_limit integer,
  quota_remaining integer,
  quota_reset_at timestamptz
)
language plpgsql
security definer
set search_path = ''
set statement_timeout = '5s'
as $$
declare
  auth_context record;
  identity_pepper bytea;
  external_hash bytea;
  request_hash bytea;
  existing_receipt loyalty_private.service_customer_command_receipts%rowtype;
  target_identity loyalty_private.service_customer_identities%rowtype;
  target_customer loyalty.customers%rowtype;
  command_outcome text;
  command_time timestamptz := clock_timestamp();
begin
  if target_external_customer_id is null
    or target_external_customer_id <> btrim(target_external_customer_id)
    or length(target_external_customer_id) not between 1 and 200
    or target_external_customer_id ~ '[[:cntrl:]]'
    or target_idempotency_key is null
    or target_idempotency_key <> btrim(target_idempotency_key)
    or target_idempotency_key !~ '^[A-Za-z0-9._:-]{1,255}$'
    or target_correlation_id is null then
    raise exception using errcode = '22023', message = 'invalid service customer command';
  end if;
  select * into strict auth_context
  from loyalty_private.authorize_service_account_request_v1(
    target_credential_public_id, target_token_sha256, 'customers:write'
  );
  select secret.pepper into strict identity_pepper
  from loyalty_private.service_account_identity_peppers as secret
  where secret.organization_id = auth_context.organization_id
    and secret.service_account_id = auth_context.service_account_id;
  external_hash := extensions.hmac(
    convert_to(target_external_customer_id, 'UTF8'), identity_pepper, 'sha256'
  );
  request_hash := extensions.digest(convert_to(
    'service-customer.upsert|' || auth_context.service_account_public_id::text ||
      '|' || encode(external_hash, 'hex'),
    'UTF8'
  ), 'sha256');
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
    'service-customer-idempotency|' || auth_context.service_account_id::text ||
      '|' || target_idempotency_key,
    auth_context.organization_id
  ));
  select receipt.* into existing_receipt
  from loyalty_private.service_customer_command_receipts as receipt
  where receipt.organization_id = auth_context.organization_id
    and receipt.service_account_id = auth_context.service_account_id
    and receipt.idempotency_key = target_idempotency_key;
  if found then
    if existing_receipt.request_sha256 <> request_hash then
      raise exception using errcode = '23514', message = 'service customer idempotency conflict';
    end if;
    return query select customer.public_id, 'duplicate'::text,
      auth_context.quota_limit, auth_context.quota_remaining,
      auth_context.quota_reset_at
    from loyalty.customers as customer
    where customer.organization_id = auth_context.organization_id
      and customer.id = existing_receipt.customer_id;
    return;
  end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
    'service-customer|' || auth_context.service_account_id::text || '|' ||
      encode(external_hash, 'hex'),
    auth_context.organization_id
  ));
  select identity.* into target_identity
  from loyalty_private.service_customer_identities as identity
  where identity.organization_id = auth_context.organization_id
    and identity.service_account_id = auth_context.service_account_id
    and identity.external_customer_sha256 = external_hash;
  if found then
    select customer.* into target_customer
    from loyalty.customers as customer
    where customer.organization_id = auth_context.organization_id
      and customer.id = target_identity.customer_id
      and customer.status = 'active';
    if not found then
      raise exception using errcode = '23514', message = 'service customer unavailable';
    end if;
    command_outcome := 'existing';
  else
    insert into loyalty.customers (organization_id, display_reference, created_at, updated_at)
    values (auth_context.organization_id, null, command_time, command_time)
    returning * into strict target_customer;
    insert into loyalty_private.service_customer_identities (
      organization_id, service_account_id, customer_id,
      external_customer_sha256, created_at
    ) values (
      auth_context.organization_id, auth_context.service_account_id,
      target_customer.id, external_hash, command_time
    );
    command_outcome := 'created';
  end if;
  insert into loyalty_private.service_customer_command_receipts (
    organization_id, service_account_id, customer_id,
    external_customer_sha256, idempotency_key, request_sha256,
    original_outcome, correlation_id, created_at
  ) values (
    auth_context.organization_id, auth_context.service_account_id,
    target_customer.id, external_hash, target_idempotency_key,
    request_hash, command_outcome, target_correlation_id, command_time
  );
  return query select target_customer.public_id, command_outcome,
    auth_context.quota_limit, auth_context.quota_remaining,
    auth_context.quota_reset_at;
end;
$$;

create or replace function loyalty_private.accept_service_activity_v1(
  target_credential_public_id uuid,
  target_token_sha256 bytea,
  target_external_customer_id text,
  target_event_id text,
  target_occurred_at timestamptz,
  target_source text,
  target_activity_code text,
  target_product_id text,
  target_category_ids text[],
  target_idempotency_key text,
  target_correlation_id uuid
)
returns table (
  receipt_id uuid,
  receipt_outcome text,
  canonical_event_id uuid,
  canonical_outcome text,
  quota_limit integer,
  quota_remaining integer,
  quota_reset_at timestamptz
)
language plpgsql
security definer
set search_path = ''
set statement_timeout = '5s'
as $$
declare
  auth_context record;
  identity_pepper bytea;
  external_hash bytea;
  target_identity loyalty_private.service_customer_identities%rowtype;
  target_customer loyalty.customers%rowtype;
  source_delivery_id text;
  source_event_id text;
  raw_body jsonb;
  body_sha256 text;
  accepted record;
  normalized record;
  command_time timestamptz := clock_timestamp();
begin
  if target_external_customer_id is null
    or target_external_customer_id <> btrim(target_external_customer_id)
    or length(target_external_customer_id) not between 1 and 200
    or target_external_customer_id ~ '[[:cntrl:]]'
    or target_event_id is null
    or target_event_id !~ '^[A-Za-z0-9._:-]{1,255}$'
    or target_occurred_at is null
    or target_occurred_at < command_time - interval '10 years'
    or target_occurred_at > command_time + interval '5 minutes'
    or target_source is null
    or target_source not in (
      'account_created', 'birthday', 'verified_product_review',
      'referral', 'custom_activity'
    )
    or target_activity_code is null
    or target_activity_code !~ '^[a-z][a-z0-9_-]{0,79}$'
    or target_category_ids is null
    or cardinality(target_category_ids) > 100
    or exists (
      select 1 from unnest(target_category_ids) as category_id
      where category_id is null or length(btrim(category_id)) not between 1 and 255
    )
    or target_idempotency_key is null
    or target_idempotency_key !~ '^[A-Za-z0-9._:-]{1,255}$'
    or target_correlation_id is null
    or (target_source <> 'custom_activity' and target_activity_code <> target_source)
    or (target_source = 'verified_product_review' and (
      target_product_id is null or length(btrim(target_product_id)) not between 1 and 255
    ))
    or (target_source <> 'verified_product_review' and (
      target_product_id is not null or cardinality(target_category_ids) > 0
    )) then
    raise exception using errcode = '22023', message = 'invalid service activity command';
  end if;
  select * into strict auth_context
  from loyalty_private.authorize_service_account_request_v1(
    target_credential_public_id, target_token_sha256, 'activities:write'
  );
  select secret.pepper into strict identity_pepper
  from loyalty_private.service_account_identity_peppers as secret
  where secret.organization_id = auth_context.organization_id
    and secret.service_account_id = auth_context.service_account_id;
  external_hash := extensions.hmac(
    convert_to(target_external_customer_id, 'UTF8'), identity_pepper, 'sha256'
  );
  select identity.* into target_identity
  from loyalty_private.service_customer_identities as identity
  where identity.organization_id = auth_context.organization_id
    and identity.service_account_id = auth_context.service_account_id
    and identity.external_customer_sha256 = external_hash;
  if not found then
    raise exception using errcode = 'P0002', message = 'service customer not found';
  end if;
  select customer.* into target_customer
  from loyalty.customers as customer
  where customer.organization_id = auth_context.organization_id
    and customer.id = target_identity.customer_id
    and customer.status = 'active';
  if not found then
    raise exception using errcode = '23514', message = 'service customer unavailable';
  end if;

  source_delivery_id := 'service-api:' || auth_context.service_account_public_id::text ||
    ':' || encode(extensions.digest(convert_to(target_idempotency_key, 'UTF8'), 'sha256'), 'hex');
  source_event_id := 'service-api:' || auth_context.service_account_public_id::text ||
    ':' || encode(extensions.digest(convert_to(target_event_id, 'UTF8'), 'sha256'), 'hex');
  raw_body := jsonb_build_object(
    'version', '1',
    'deliveryId', source_delivery_id,
    'sourceId', auth_context.connection_public_id,
    'eventId', source_event_id,
    'occurredAt', target_occurred_at,
    'deliveredAt', target_occurred_at,
    'correlationId', target_correlation_id,
    'payload', jsonb_build_object(
      'kind', 'activity',
      'source', target_source,
      'customerId', target_customer.public_id,
      'activityCode', target_activity_code,
      'productId', target_product_id,
      'categoryIds', to_jsonb(target_category_ids)
    )
  );
  body_sha256 := encode(extensions.digest(convert_to(raw_body::text, 'UTF8'), 'sha256'), 'hex');
  select * into strict accepted
  from loyalty_private.accept_commerce_delivery(
    auth_context.organization_id, auth_context.connection_id,
    source_delivery_id, '1', source_event_id,
    'commerce.activity.recorded', target_customer.public_id::text, null,
    target_occurred_at, command_time, 'v1',
    auth_context.credential_public_id::text, body_sha256, raw_body
  );
  select * into strict normalized
  from loyalty_private.normalize_commerce_delivery(accepted.receipt_id, 'v1');
  return query select accepted.receipt_id, accepted.outcome,
    normalized.canonical_event_id, normalized.outcome,
    auth_context.quota_limit, auth_context.quota_remaining,
    auth_context.quota_reset_at;
end;
$$;

create or replace function loyalty.get_my_service_accounts_v1(
  target_organization_public_id uuid
)
returns table (document jsonb)
language plpgsql
stable
security definer
set search_path = ''
set statement_timeout = '5s'
as $$
declare
  target_organization loyalty.organizations%rowtype;
begin
  select organization.* into target_organization
  from loyalty.organizations as organization
  where organization.public_id = target_organization_public_id
    and loyalty_private.has_organization_role(
      organization.id, array['owner', 'admin']::text[]
    );
  if not found then
    raise exception using errcode = '42501', message = 'service account read not authorized';
  end if;
  return query
  select jsonb_build_object(
    'version', '1',
    'serviceAccounts', coalesce(jsonb_agg(jsonb_build_object(
      'id', account.public_id,
      'workspaceId', workspace.public_id,
      'workspaceName', workspace.name,
      'programmeId', programme.public_id,
      'programmeName', programme.name,
      'displayName', account.display_name,
      'scopes', to_jsonb(account.scopes),
      'requestsPerMinute', account.requests_per_minute,
      'status', account.status,
      'createdAt', account.created_at,
      'credentials', coalesce((
        select jsonb_agg(jsonb_build_object(
          'id', credential.public_id,
          'secretHint', credential.secret_hint,
          'status', case
            when credential.status = 'retiring'
              and credential.valid_until <= now() then 'expired'
            else credential.status end,
          'validUntil', credential.valid_until,
          'createdAt', credential.created_at,
          'revokedAt', credential.revoked_at
        ) order by credential.created_at desc, credential.id desc)
        from (
          select candidate.*
          from loyalty_private.service_account_credentials as candidate
          where candidate.organization_id = account.organization_id
            and candidate.service_account_id = account.id
          order by candidate.created_at desc, candidate.id desc
          limit 100
        ) as credential
      ), '[]'::jsonb)
    ) order by account.created_at desc, account.id desc), '[]'::jsonb)
  )
  from (
    select candidate.*
    from loyalty.service_accounts as candidate
    where candidate.organization_id = target_organization.id
    order by candidate.created_at desc, candidate.id desc
    limit 100
  ) as account
  join loyalty.workspaces as workspace
    on workspace.organization_id = account.organization_id
   and workspace.id = account.workspace_id
  join loyalty.programmes as programme
    on programme.organization_id = account.organization_id
   and programme.id = account.programme_id
  ;
end;
$$;

alter function loyalty_private.protect_service_account_credential() owner to loyalty_owner;
alter function loyalty_private.create_service_account_v1(
  uuid, uuid, uuid, text, text[], integer, text, uuid
) owner to loyalty_owner;
alter function loyalty_private.issue_service_account_credential_v1(
  uuid, uuid, uuid, bytea, text, integer, text, uuid
) owner to loyalty_owner;
alter function loyalty_private.revoke_service_account_credential_v1(
  uuid, uuid, uuid, text, text, uuid
) owner to loyalty_owner;
alter function loyalty_private.authorize_service_account_request_v1(
  uuid, bytea, text
) owner to loyalty_owner;
alter function loyalty_private.upsert_service_customer_v1(
  uuid, bytea, text, text, uuid
) owner to loyalty_owner;
alter function loyalty_private.accept_service_activity_v1(
  uuid, bytea, text, text, timestamptz, text, text, text, text[], text, uuid
) owner to loyalty_owner;
alter function loyalty.get_my_service_accounts_v1(uuid) owner to loyalty_owner;

revoke all on loyalty.service_accounts,
  loyalty_private.service_account_credentials,
  loyalty_private.service_account_identity_peppers,
  loyalty_private.service_customer_identities,
  loyalty_private.service_customer_command_receipts,
  loyalty_private.service_account_rate_windows
  from public, anon, authenticated, loyalty_runtime, loyalty_worker;

revoke all on function loyalty_private.protect_service_account_credential(),
  loyalty_private.create_service_account_v1(
    uuid, uuid, uuid, text, text[], integer, text, uuid
  ),
  loyalty_private.issue_service_account_credential_v1(
    uuid, uuid, uuid, bytea, text, integer, text, uuid
  ),
  loyalty_private.revoke_service_account_credential_v1(
    uuid, uuid, uuid, text, text, uuid
  ),
  loyalty_private.authorize_service_account_request_v1(uuid, bytea, text),
  loyalty_private.upsert_service_customer_v1(uuid, bytea, text, text, uuid),
  loyalty_private.accept_service_activity_v1(
    uuid, bytea, text, text, timestamptz, text, text, text, text[], text, uuid
  )
  from public, anon, authenticated, loyalty_runtime, loyalty_worker;

revoke all on function loyalty.get_my_service_accounts_v1(uuid)
  from public, anon, authenticated, loyalty_runtime, loyalty_worker;

grant execute on function loyalty_private.create_service_account_v1(
  uuid, uuid, uuid, text, text[], integer, text, uuid
),
  loyalty_private.issue_service_account_credential_v1(
    uuid, uuid, uuid, bytea, text, integer, text, uuid
  ),
  loyalty_private.revoke_service_account_credential_v1(
    uuid, uuid, uuid, text, text, uuid
  ),
  loyalty_private.upsert_service_customer_v1(uuid, bytea, text, text, uuid),
  loyalty_private.accept_service_activity_v1(
    uuid, bytea, text, text, timestamptz, text, text, text, text[], text, uuid
  )
  to loyalty_runtime;

grant execute on function loyalty.get_my_service_accounts_v1(uuid)
  to authenticated;

comment on table loyalty.service_accounts is
  'Immutable organization/workspace/programme scope and least-privilege quota for one external server integration; no credential material.';
comment on table loyalty_private.service_account_credentials is
  'Private high-entropy bearer-token digests and monotonic lifecycle state; raw tokens are never persisted.';
comment on table loyalty_private.service_account_identity_peppers is
  'Private random per-service-account key for non-reversible external-customer HMAC fingerprints.';
comment on table loyalty_private.service_customer_identities is
  'Immutable service-account namespace mapping from a hashed external identity to one tenant customer; never email-derived.';
comment on table loyalty_private.service_account_rate_windows is
  'Database-authoritative fixed-minute successful-request counters partitioned by credential.';
comment on function loyalty_private.upsert_service_customer_v1(
  uuid, bytea, text, text, uuid
) is 'Authenticates one scoped credential, applies its quota, and idempotently creates one hashed external customer mapping without caller tenant authority.';
comment on function loyalty_private.accept_service_activity_v1(
  uuid, bytea, text, text, timestamptz, text, text, text, text[], text, uuid
) is 'Authenticates one scoped credential and appends a minimized Merchant Activity fact through the existing canonical inbox and normalization fences.';
